name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Instala as dependências do Cypress
      - name: Install Cypress
        run: |
             npm install cypress
             npx verify

      # Executa os testes com Cypress
      - name: Run Cypress tests
        run: npx cypress run
